const fs = require('node:fs')
const path = require('node:path')
const { execSync } = require('node:child_process')

const repoRoot = path.resolve(__dirname, '..')
const outputPaths = [
  path.join(repoRoot, 'src', 'OmegaScans', 'version.ts'),
  path.join(repoRoot, 'src', 'MangaDistrict', 'version.ts')
]

function dateParts(timeZone) {
  const parts = new Intl.DateTimeFormat('en-GB', {
    timeZone,
    year: 'numeric',
    month: 'numeric',
    day: 'numeric'
  }).formatToParts(new Date())

  const values = Object.fromEntries(parts.map(part => [part.type, part.value]))

  return {
    year: values.year,
    month: String(Number(values.month)),
    day: String(Number(values.day))
  }
}

function buildNumber() {
  const explicit = process.env.PAPERBACK_BUILD_NUMBER ?? process.env.GITHUB_RUN_NUMBER

  if (explicit && /^\d+$/.test(explicit)) {
    return explicit
  }

  try {
    return execSync('git rev-list --count HEAD', {
      cwd: repoRoot,
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore']
    }).trim()
  } catch {
    return '0'
  }
}

const timeZone = process.env.PAPERBACK_VERSION_TIMEZONE || 'Europe/Paris'
const { year, month, day } = dateParts(timeZone)
const version = `${year}.${month}.${day}.${buildNumber()}`
const content = `// This file is generated by scripts/generate-version.js.\nexport const BUILD_VERSION = '${version}'\n`

for (const outputPath of outputPaths) {
  fs.writeFileSync(outputPath, content)
}

console.log(`Generated Paperback source version ${version}`)
